### PR TITLE
Add support for arrays of elements

### PR DESCRIPTION
**Pull request by estrattonbailey**
This is a beautiful little library! I finally got around to messing with it today. 

I realize it's marked experimental, but I happened upon a use case where I wanted to render a series of similar elements from an array of imported data. So maybe this is out of your intended scope – I don't even know if you plan to field PRs on this project – but here's the solution I came up with. 

Tests and README included. Hope it's helpful :)

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks! Will take a look. For arrays, I've just been spreading arrays as arguments like here https://github.com/jxnblk/hello-color/blob/master/demo/index.js#L124

e.g.

``` js
h('ul')(
  ...items.map(item => h('li')(item))
)
```

**Comment by estrattonbailey** [comment]
Ahhh, lovely, never seen that pattern before! That'll do it for me, thanks man.

**Comment by jxnblk** [comment]
FWIW, I _do_ like the idea of supporting array here too. Happy to take a look again if you still wanna contribute ✌️

**Comment by estrattonbailey** [comment]
Happy to, let me know what you need!

**Pull request closed without merging**
